eureka:
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url: 
      default-zone: ${EUREKA_URI:http://localhost:8761/eureka}
  instance: 
    prefer-ip-address: true

spring:
  application:
    name: product-micro-service  data:    mongodb:      uri: place your db uri
server:  port: 8088
  
